export const BOARD_W = 5;
export const BOARD_H = 5;
export const BLUE = 0;
export const RED = 1;
export const GUESSER = 0;
export const GIVER = 1;
export const LOADING = 0; // TODO: never used
export const STARTING = 1;
export const MENU = 2;
export const GAME = 3;
export const OVER = 4;
